Repository coders4help/volunteer_planner, pull requests merged in 2022-04, with the labels that each got.

#536 Feature/shift notification
  locale/ar/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/es_MX/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/hy/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/sk/LC_MESSAGES/django.po
  locale/sl/LC_MESSAGES/django.po
  locale/sq/LC_MESSAGES/django.po
  locale/sr_RS/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr_TR/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/zh_CN/LC_MESSAGES/django.po
  resources/custom/css/vp.css
  scheduler/admin.py
  scheduler/forms.py
  scheduler/migrations/0041_add_shift_messages.py
  scheduler/models.py
  scheduler/signals.py
  scheduler/templates/emails/shift_message_to_helpers.txt
  scheduler/templates/helpdesk_single.html
  scheduler/templates/shift_message_to_helpers.html
  scheduler/urls.py
  scheduler/views.py
Labels: ⚠️ Migration

#546 Check for user_account in get_cached_memberships
  organizations/admin.py
Labels: Bug

#559 Use tz aware datetime in filter for DateTimeFields
  scheduler/managers.py
Labels: Bug

#560 Apply timezone related fix
  scheduler/managers.py
  volunteer_planner/settings/production.py
Labels: Bug, Django4

#555 feature/changelog
  CHANGELOG.md
Labels: Django4

#565 Fix shift/-template admin when ordering by task/workplaces
  scheduler/admin.py
  scheduletemplates/admin.py
Labels: Bug, High Priority

#571 Make admin timezone aware for shift/-templates
  scheduler/models.py
  scheduletemplates/models.py
Labels: Bug, High Priority, 🌐 l10n

#598 Fix URL redirection from remote source
  content/views.py
Labels: ⚠️ Security Issue

#591 Integrate django-post-office
  requirements/base.txt
  volunteer_planner/settings/base.py
  volunteer_planner/settings/email.py
  volunteer_planner/settings/local.py
  volunteer_planner/settings/production.py
Labels: ⚠️ Migration

#608 Fix several problems with shift messages
  common/email_backend.py
  locale/ar/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/es_MX/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/hy/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/sk/LC_MESSAGES/django.po
  locale/sl/LC_MESSAGES/django.po
  locale/sq/LC_MESSAGES/django.po
  locale/sr_RS/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr_TR/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/zh_CN/LC_MESSAGES/django.po
  organizations/templatetags/memberships.py
  scheduler/migrations/0042_change_shiftmessages_shift_cascade_delete.py
  scheduler/models.py
  scheduler/signals.py
  scheduler/templates/emails/shift_message_to_helpers.txt
  scheduler/templates/helpdesk_single.html
  scheduler/templates/shift_message_to_helpers.html
  scheduler/views.py
  volunteer_planner/settings/email.py
Labels: Bug, 🌐 l10n, ⚠️ Migration, ⚠️ Security Issue

#610 fix/post office dependency
  requirements/base.txt
Labels: Bug

#616 Add "repeat e-mail address" field to sign-up form
  accounts/admin.py
  accounts/auth.py
  accounts/forms.py
  accounts/templates/user_account_delete.html
  accounts/templates/user_detail.html
  locale/ar/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/es_MX/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/hy/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/sk/LC_MESSAGES/django.po
  locale/sl/LC_MESSAGES/django.po
  locale/sq/LC_MESSAGES/django.po
  locale/sr_RS/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr_TR/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/zh_CN/LC_MESSAGES/django.po
  non_logged_in_area/templates/shelters_need_help.html
  organizations/templates/manage_members.html
  resources/angularjs/1.4.7/angular-sanitize.js
  scheduler/templates/helpdesk_single.html
  scheduler/views.py
  templates/registration/login.html
  templates/registration/password_change_form.html
  templates/registration/password_reset_confirm.html
  templates/registration/password_reset_done.html
  templates/registration/password_reset_email.html
  templates/registration/password_reset_form.html
  templates/registration/registration_complete.html
  templates/registration/registration_form.html
  tests/registration/test_registration.py
  volunteer_planner/settings/email.py
Labels: Enhancement, Story/Use-Case, 🌐 l10n

#632 Fix error on template creation
  scheduletemplates/admin.py
Labels: Bug

#631 Add celery support
  .dockerignore
  .env.template
  Dockerfile
  celery-entrypoint.sh
  django-entrypoint.sh
  docker-compose.yml
  docker/docker-compose.yml
  requirements/base.txt
  volunteer_planner/settings/base.py
  volunteer_planner/settings/email.py
  worker/__init__.py
  worker/celery.py
Labels: Enhancement

#633 Improve docker build
  .dockerignore
  Dockerfile
  docker/db/Dockerfile
  docker/web/Dockerfile
Labels: Enhancement
