Repository coders4help/volunteer_planner, pull requests merged in 2022-03, with the labels that each got.

#448 feature/admin UI registration management
  accounts/admin.py
Labels: enhancement

#453 Fix shift template name
  scheduletemplates/models.py
Labels: bug

#457 feature/admin UI registration management
  accounts/admin.py
Labels: enhancement

#487 Change python to python3
  manage.py
Labels: Enhancement, Low Priority

#490 Expose less user information to managers
  accounts/admin.py
  locale/cs/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
Labels: Bug, High Priority

#526 Make number of slots in shifts and templates > 0
  locale/ar/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/es_MX/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/hy/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/sk/LC_MESSAGES/django.po
  locale/sl/LC_MESSAGES/django.po
  locale/sq/LC_MESSAGES/django.po
  locale/sr_RS/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr_TR/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/zh_CN/LC_MESSAGES/django.po
  scheduler/migrations/0040_min_shift_slots.py
  scheduler/models.py
  scheduletemplates/migrations/0006_min_shift_slots.py
  scheduletemplates/models.py
Labels: ⚠️ Migration

#524 Make membership unique per user and facility/org
  organizations/migrations/0017_make_memberships_unique.py
  organizations/models.py
Labels: ⚠️ Migration

#530 Fix order of tasks and workplaces
  organizations/migrations/0018_alter_ordering_by_priority.py
  organizations/models.py
  scheduler/views.py
Labels: ⚠️ Migration

#538 Update translations 🇺🇦 🇩🇪 🇨🇿
  accounts/forms.py
  content/migrations/0005_alter_flatpagetranslation_language.py
  locale/ar/LC_MESSAGES/django.po
  locale/bg/LC_MESSAGES/django.po
  locale/cs/LC_MESSAGES/django.po
  locale/da/LC_MESSAGES/django.po
  locale/de/LC_MESSAGES/django.po
  locale/el/LC_MESSAGES/django.po
  locale/en/LC_MESSAGES/django.po
  locale/es/LC_MESSAGES/django.po
  locale/es_MX/LC_MESSAGES/django.po
  locale/fa/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/hr/LC_MESSAGES/django.po
  locale/hu/LC_MESSAGES/django.po
  locale/hy/LC_MESSAGES/django.po
  locale/it/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
  locale/no/LC_MESSAGES/django.po
  locale/pl/LC_MESSAGES/django.po
  locale/pt/LC_MESSAGES/django.po
  locale/pt_BR/LC_MESSAGES/django.po
  locale/ro/LC_MESSAGES/django.po
  locale/ru/LC_MESSAGES/django.po
  locale/sk/LC_MESSAGES/django.po
  locale/sl/LC_MESSAGES/django.po
  locale/sq/LC_MESSAGES/django.po
  locale/sr_RS/LC_MESSAGES/django.po
  locale/sv/LC_MESSAGES/django.po
  locale/tr/LC_MESSAGES/django.po
  locale/tr_TR/LC_MESSAGES/django.po
  locale/uk/LC_MESSAGES/django.po
  locale/zh_CN/LC_MESSAGES/django.po
  scheduler/managers.py
  scheduler/settings.py
  tests/registration/test_registration.py
  tests/scheduler/test_models.py
  volunteer_planner/settings/base.py
  volunteer_planner/settings/local.py
  volunteer_planner/settings/production.py
  volunteer_planner/settings/tests.py
Labels: ⚠️ Migration
